/**
 * WARNING - do not edit this file - used to run tests
 */

"use strict";

module.exports = {
    "app": {
        "format": "csv", // json, csv
        "write_to_file": false // true, false
    },
    "hash": "fd4f0cfef1807e327476ff60288bea78",
    "auth": {
        "username": "CS_2",
        "api_key": "5c15152f7086f7f3b2d2cc6b25648e94"
    },
    "analysis": {
        "freqDist": [
        ],
        "timeSeries": [
        ]
    }
};
