/**
 * WARNING - do not edit this file - used to run tests
 */

"use strict";
module.exports = {
    "app": {
        "format": "csv", // json, csv
        "write_to_file": false // true, false
    },
    "hash": "<INDEX_HASH>",
    "auth": {
        "username": "<USERNNAME>",
        "api_key": "<API_KEY>"
    },
    "analysis": {
        "freqDist": [
        ],
        "timeSeries": [
        ]
    }
};
